# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acceptdestruction.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_acceptDestruction(object):
    def setupUi(self, acceptDestruction):
        acceptDestruction.setObjectName("acceptDestruction")
        acceptDestruction.resize(472, 242)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        acceptDestruction.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(acceptDestruction)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 201, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 221, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 180, 84, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(273, 180, 101, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 160, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 421, 91))
        self.label_3.setObjectName("label_3")
        acceptDestruction.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(acceptDestruction)
        self.statusbar.setObjectName("statusbar")
        acceptDestruction.setStatusBar(self.statusbar)

        self.retranslateUi(acceptDestruction)
        QtCore.QMetaObject.connectSlotsByName(acceptDestruction)

    def retranslateUi(self, acceptDestruction):
        _translate = QtCore.QCoreApplication.translate
        acceptDestruction.setWindowTitle(_translate("acceptDestruction", "Attention Required"))
        self.label.setText(_translate("acceptDestruction", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Terms of Conditions</span></p></body></html>"))
        self.label_2.setText(_translate("acceptDestruction", "Please accept the terms of conditions\n"
" in order to continue"))
        self.pushButton.setText(_translate("acceptDestruction", "Accept"))
        self.pushButton_2.setText(_translate("acceptDestruction", "DON\'T accept"))
        self.label_3.setText(_translate("acceptDestruction", "Any possible damage caused by this program is this program\'s user\'s\n"
" responsability and NOT the author\'s\n"
"\n"
"This program is not to be redistributed."))
