# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminprompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_administratorRequired(object):
    def setupUi(self, administratorRequired):
        administratorRequired.setObjectName("administratorRequired")
        administratorRequired.resize(271, 168)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        administratorRequired.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(administratorRequired)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 10, 251, 18))
        self.titleLabel.setObjectName("titleLabel")
        self.contentLabel = QtWidgets.QLabel(self.centralwidget)
        self.contentLabel.setGeometry(QtCore.QRect(20, 40, 221, 51))
        self.contentLabel.setObjectName("contentLabel")
        self.buttonOk = QtWidgets.QPushButton(self.centralwidget)
        self.buttonOk.setGeometry(QtCore.QRect(90, 110, 84, 34))
        self.buttonOk.setObjectName("buttonOk")
        self.buttonOk.clicked.connect(sys.exit) # stop program when OK is clicked
        administratorRequired.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(administratorRequired)
        self.statusbar.setObjectName("statusbar")
        administratorRequired.setStatusBar(self.statusbar)

        self.retranslateUi(administratorRequired)
        QtCore.QMetaObject.connectSlotsByName(administratorRequired)

    def retranslateUi(self, administratorRequired):
        _translate = QtCore.QCoreApplication.translate
        administratorRequired.setWindowTitle(_translate("administratorRequired", "Administrator Required"))
        self.titleLabel.setText(_translate("administratorRequired", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Administrator Rights Required</span></p></body></html>"))
        self.contentLabel.setText(_translate("administratorRequired", "Windows Administrator is required to\n"
" run this program. Right Click on exe\n"
" and click \"Run as administrator\"."))
        self.buttonOk.setText(_translate("administratorRequired", "OK"))


def show():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    administratorRequired = QtWidgets.QMainWindow()
    ui = Ui_administratorRequired()
    ui.setupUi(administratorRequired)
    administratorRequired.show()
    sys.exit(app.exec_())
