[package]
name = "windowsbloatwareremover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = "0.3.16"
eframe = "0.20.1"
egui = "0.20.1"
