# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import process
import sys
app = QtWidgets.QApplication(sys.argv)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 481)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(40, 20, 521, 71))
        self.titleLabel.setScaledContents(False)
        self.titleLabel.setObjectName("titleLabel")
        self.actionLabel = QtWidgets.QLabel(self.centralwidget)
        self.actionLabel.setGeometry(QtCore.QRect(50, 100, 111, 17))
        self.actionLabel.setObjectName("actionLabel")
        self.buttonAll = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAll.setGeometry(QtCore.QRect(40, 120, 351, 71))
        self.buttonAll.setObjectName("buttonAll")
        self.buttonAll.clicked.connect(lambda:MainWindow.close())
        self.buttonBing = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBing.setGeometry(QtCore.QRect(40, 200, 351, 25))
        self.buttonBing.setObjectName("buttonBing")
        self.buttonBing.clicked.connect(lambda:process.show("bing"))
        self.buttonXbox = QtWidgets.QPushButton(self.centralwidget)
        self.buttonXbox.setGeometry(QtCore.QRect(40, 230, 351, 25))
        self.buttonXbox.setObjectName("buttonXbox")
        self.buttonXbox.clicked.connect(lambda:process.show("xbox"))
        self.buttonUsual = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUsual.setGeometry(QtCore.QRect(40, 260, 351, 71))
        self.buttonUsual.setObjectName("buttonUsual")
        self.buttonUsual.clicked.connect(lambda:process.show("usual"))
        self.buttonCustom = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCustom.setGeometry(QtCore.QRect(40, 370, 351, 25))
        self.buttonCustom.setObjectName("buttonCustom")
        self.buttonCustom.clicked.connect(lambda:process.show("custom"))
        self.listBing = QtWidgets.QLabel(self.centralwidget)
        self.listBing.setGeometry(QtCore.QRect(400, 200, 451, 20))
        self.listBing.setObjectName("listBing")
        self.listAll = QtWidgets.QLabel(self.centralwidget)
        self.listAll.setGeometry(QtCore.QRect(400, 120, 471, 71))
        self.listAll.setObjectName("listAll")
        self.listXbox = QtWidgets.QLabel(self.centralwidget)
        self.listXbox.setGeometry(QtCore.QRect(400, 230, 451, 20))
        self.listXbox.setObjectName("listXbox")
        self.listUsual = QtWidgets.QLabel(self.centralwidget)
        self.listUsual.setGeometry(QtCore.QRect(400, 260, 461, 71))
        self.listUsual.setObjectName("listUsual")
        self.buttonEdge = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEdge.setGeometry(QtCore.QRect(40, 340, 351, 25))
        self.buttonEdge.setObjectName("buttonEdge")
        self.listEdge = QtWidgets.QLabel(self.centralwidget)
        self.listEdge.setGeometry(QtCore.QRect(400, 340, 451, 20))
        self.listEdge.setObjectName("listEdge")
        self.listCustom = QtWidgets.QLabel(self.centralwidget)
        self.listCustom.setGeometry(QtCore.QRect(400, 370, 451, 20))
        self.listCustom.setObjectName("listCustom")
        self.listLabel = QtWidgets.QLabel(self.centralwidget)
        self.listLabel.setGeometry(QtCore.QRect(400, 100, 181, 17))
        self.listLabel.setObjectName("listLabel")
        self.labelCredits = QtWidgets.QLabel(self.centralwidget)
        self.labelCredits.setGeometry(QtCore.QRect(570, 50, 101, 18))
        self.labelCredits.setObjectName("labelCredits")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 888, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.actionGet_Help_Online = QtWidgets.QAction(MainWindow)
        self.actionGet_Help_Online.setObjectName("actionGet_Help_Online")
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionCredits)
        self.menuHelp.addAction(self.actionGet_Help_Online)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Windows Bloatware Removal Tool"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Welcome to the Windows Bloatware Removal Tool v0.1.2</span></p></body></html>"))
        self.actionLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Select an Action:</span></p></body></html>"))
        self.buttonAll.setText(_translate("MainWindow", "Remove all preinstalled unremovable Apps from Windows"))
        self.buttonBing.setText(_translate("MainWindow", "Remove all Bing related Apps from Windows"))
        self.buttonXbox.setText(_translate("MainWindow", "Remove all Xbox related Apps from Windows"))
        self.buttonUsual.setText(_translate("MainWindow", "Remove all Apps that You would usually\n"
" remove from Windows"))
        self.buttonCustom.setText(_translate("MainWindow", "Remove a custom selection of Apps from Windows"))
        self.listBing.setText(_translate("MainWindow", "Finance, News, Sports, Weather"))
        self.listAll.setText(_translate("MainWindow", "3D Builder, Alarms, Calculator, Communications, Camera, Cortana, Get Office,\n"
" Skype, Get Started, Groove Music, Maps, News, One Note, People, Solitaire\n"
" Collection, Finance, Video & TV, Photos, Microsoft Store, Sports, Voice Recorder,\n"
" Weather, Xbox, Xbox Gaming Overlay, Get Help, Your Phone, Cortana, Edge"))
        self.listXbox.setText(_translate("MainWindow", "Xbox, Xbox Game Bar"))
        self.listUsual.setText(_translate("MainWindow", "3D Builder, Alarms, Communications, Camera, Cortana, Get Office, Skype,\n"
" Get Started, Groove Music, Maps, News, One Note, People, Solitaire Collection,\n"
" Finance, Sports, Voice Recorder, Weather, Xbox, Get Help, Your Phone, Cortana,\n"
" Edge"))
        self.buttonEdge.setText(_translate("MainWindow", "Remove Microsoft Edge from Windows"))
        self.listEdge.setText(_translate("MainWindow", "Edge"))
        self.listCustom.setText(_translate("MainWindow", "Custom..."))
        self.listLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Apps that will be removed:</span></p></body></html>"))
        self.labelCredits.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">by Jonas_jones</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCredits.setText(_translate("MainWindow", "Credits"))
        self.actionGet_Help_Online.setText(_translate("MainWindow", "Get Help Online"))


def show():
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()
